### ISSUE TITLE
Styling etc.

### ISSUE THREAD

**Issue by cfujiname** [Catzkorn/makersbnb#19]

**Comment by 0xfarhaan** [comment]
- [x] We want to add signup form text on main page
- [x] add a navbar to '/spaces/ route try make it come out the side.
- [ ] '/spaces' route show the different spaces in boxes and nice to have - random image of a house selected for each
- [ ] '/spaces/myspaces' route show the different spaces in boxes and nice to have - random image of a house selected for each
- [x] style our flash notices 
- [x] style the create space page to look like signup page
- [x] style login page like signup page
- [x] think about how to show logo on every page
